Repository Onmoim/Onmoim-Backend, pull requests merged in 2025-06, with the labels that each got.

#60 refactor: 회원가입과 관심사 선택 api 분리, feat: 프로필 조회
  build.gradle
  src/main/java/com/onmoim/server/common/exception/ErrorCode.java
  src/main/java/com/onmoim/server/config/SecurityConfig.java
  src/main/java/com/onmoim/server/location/repository/LocationRepository.java
  src/main/java/com/onmoim/server/oauth/constant/OAuthApiConstants.java
  src/main/java/com/onmoim/server/oauth/service/provider/GoogleOAuthProvider.java
  src/main/java/com/onmoim/server/oauth/service/provider/KakaoOAuthProvider.java
  src/main/java/com/onmoim/server/oauth/service/provider/OAuthProvider.java
  src/main/java/com/onmoim/server/oauth/service/provider/OAuthProviderFactory.java
  src/main/java/com/onmoim/server/user/controller/UserController.java
  src/main/java/com/onmoim/server/user/dto/request/CreateUserCategoryRequestDto.java
  src/main/java/com/onmoim/server/user/dto/request/SignupRequestDto.java
  src/main/java/com/onmoim/server/user/dto/response/ProfileResponseDto.java
  src/main/java/com/onmoim/server/user/entity/User.java
  src/main/java/com/onmoim/server/user/mapper/UserMapper.java
  src/main/java/com/onmoim/server/user/mapper/UserMapperCustom.java
  src/main/java/com/onmoim/server/user/mapper/UserMapperCustomImpl.java
  src/main/java/com/onmoim/server/user/repository/UserCategoryRepository.java
  src/main/java/com/onmoim/server/user/service/UserService.java
  src/main/java/com/onmoim/server/user/service/impl/UserServiceImpl.java
  src/test/java/com/onmoim/server/user/service/UserServiceTest.java
Labels: ✨ feat, 💻 refactor

#56 Feat: 채팅방 만들기 기능
  build.gradle
  src/main/java/com/onmoim/server/OnmoimApplication.java
  src/main/java/com/onmoim/server/chat/config/CustomWebSocketAnnotationMethodMessageHandler.java
  src/main/java/com/onmoim/server/chat/config/StompInboundThreadPoolConfig.java
  src/main/java/com/onmoim/server/chat/config/StompRejectedHandler.java
  src/main/java/com/onmoim/server/chat/config/WebSocketConfig.java
  src/main/java/com/onmoim/server/chat/config/WebSocketEventListener.java
  src/main/java/com/onmoim/server/chat/controller/ChatMessageSocketController.java
  src/main/java/com/onmoim/server/chat/controller/ChatRoomRestController.java
  src/main/java/com/onmoim/server/chat/dto/ChatMessageDto.java
  src/main/java/com/onmoim/server/chat/dto/ChatRoomResponse.java
  src/main/java/com/onmoim/server/chat/dto/CreateRoomRequest.java
  src/main/java/com/onmoim/server/chat/entity/ChatRoom.java
  src/main/java/com/onmoim/server/chat/entity/ChatRoomMember.java
  src/main/java/com/onmoim/server/chat/entity/ChatRoomMessage.java
  src/main/java/com/onmoim/server/chat/entity/ChatRoomMessageId.java
  src/main/java/com/onmoim/server/chat/entity/ChatSequence.java
  src/main/java/com/onmoim/server/chat/entity/DeliveryStatus.java
  src/main/java/com/onmoim/server/chat/entity/MessageType.java
  src/main/java/com/onmoim/server/chat/entity/SubscribeRegistry.java
  src/main/java/com/onmoim/server/chat/example/SocketTestController.java
  src/main/java/com/onmoim/server/chat/example/TestChatMessage.java
  src/main/java/com/onmoim/server/chat/facade/ChatMessageFacade.java
  src/main/java/com/onmoim/server/chat/facade/ChatRoomFacade.java
  src/main/java/com/onmoim/server/chat/repository/ChatMessageRepository.java
  src/main/java/com/onmoim/server/chat/repository/ChatRoomMemberRepository.java
  src/main/java/com/onmoim/server/chat/repository/ChatRoomRepository.java
  src/main/java/com/onmoim/server/chat/service/ChatMessageEventHandler.java
  src/main/java/com/onmoim/server/chat/service/ChatMessageRetryService.java
  src/main/java/com/onmoim/server/chat/service/ChatMessageService.java
  src/main/java/com/onmoim/server/chat/service/ChatRoomMemberQueryService.java
  src/main/java/com/onmoim/server/chat/service/ChatRoomService.java
  src/main/java/com/onmoim/server/chat/service/ChatSequenceRepository.java
  src/main/java/com/onmoim/server/chat/service/InMemoryRoomChatMessageIdGenerator.java
  src/main/java/com/onmoim/server/chat/service/MessageSendEvent.java
  src/main/java/com/onmoim/server/chat/service/RoomChatMessageIdGenerator.java
  src/main/java/com/onmoim/server/common/exception/ErrorCode.java
  src/main/java/com/onmoim/server/group/service/GroupService.java
  src/test/java/com/onmoim/server/chat/ChatWebSocketIntegrationTest.java
  src/test/java/com/onmoim/server/chat/controller/ChatRoomRestControllerTest.java
  src/test/java/com/onmoim/server/chat/service/ChatRoomServiceTest.java
  src/test/java/com/onmoim/server/chat/service/TestChatMessageEventHandlerIntegrationTest.java
  src/test/java/com/onmoim/server/chat/service/TestChatMessageRetryServiceIntegrationTest.java
  src/test/java/com/onmoim/server/chat/service/TestChatMessageServiceIntegrationTest.java
Labels: ✨ feat

#62 fix: user 테스트 코드 수정
  src/test/java/com/onmoim/server/user/service/UserServiceTest.java
Labels: 🛠️ fix

#68 fix: RedisConfig 수정
  src/main/java/com/onmoim/server/config/RedisConfig.java
  src/main/java/com/onmoim/server/config/SecurityConfig.java
  src/main/java/com/onmoim/server/oauth/service/impl/RefreshTokenServiceImpl.java
Labels: 🛠️ fix

#65 [Meeting] 일정 관리 도메인 구현
  src/main/java/com/onmoim/server/common/GeoPoint.java
  src/main/java/com/onmoim/server/common/exception/ErrorCode.java
  src/main/java/com/onmoim/server/meeting/controller/MeetingController.java
  src/main/java/com/onmoim/server/meeting/dto/request/MeetingCreateRequestDto.java
  src/main/java/com/onmoim/server/meeting/dto/request/MeetingUpdateRequestDto.java
  src/main/java/com/onmoim/server/meeting/dto/response/MeetingResponseDto.java
  src/main/java/com/onmoim/server/meeting/dto/response/PageResponseDto.java
  src/main/java/com/onmoim/server/meeting/entity/Meeting.java
  src/main/java/com/onmoim/server/meeting/entity/MeetingStatus.java
  src/main/java/com/onmoim/server/meeting/entity/MeetingType.java
  src/main/java/com/onmoim/server/meeting/entity/UserMeeting.java
  src/main/java/com/onmoim/server/meeting/entity/UserMeetingId.java
  src/main/java/com/onmoim/server/meeting/repository/MeetingLockRepository.java
  src/main/java/com/onmoim/server/meeting/repository/MeetingLockRepositoryImpl.java
  src/main/java/com/onmoim/server/meeting/repository/MeetingRepository.java
  src/main/java/com/onmoim/server/meeting/repository/UserMeetingRepository.java
  src/main/java/com/onmoim/server/meeting/service/MeetingAuthService.java
  src/main/java/com/onmoim/server/meeting/service/MeetingFacadeService.java
  src/main/java/com/onmoim/server/meeting/service/MeetingQueryService.java
  src/main/java/com/onmoim/server/meeting/service/MeetingService.java
  src/main/java/com/onmoim/server/meeting/util/CursorUtils.java
  src/test/java/com/onmoim/server/meeting/entity/MeetingTest.java
  src/test/java/com/onmoim/server/meeting/service/MeetingAuthServiceTest.java
  src/test/java/com/onmoim/server/meeting/service/MeetingFacadeServiceTest.java
  src/test/java/com/onmoim/server/meeting/service/MeetingQueryServiceTest.java
  src/test/java/com/onmoim/server/meeting/service/MeetingServiceTest.java
Labels: ✨ feat

#78 [User] 로그인 및 회원가입 수정
  src/main/java/com/onmoim/server/config/SecurityConfig.java
  src/main/java/com/onmoim/server/oauth/service/OAuthService.java
  src/main/java/com/onmoim/server/oauth/service/impl/OAuthServiceImpl.java
  src/main/java/com/onmoim/server/user/controller/UserController.java
  src/main/java/com/onmoim/server/user/dto/response/SignupResponseDto.java
  src/main/java/com/onmoim/server/user/service/UserService.java
  src/main/java/com/onmoim/server/user/service/impl/UserServiceImpl.java
  src/test/java/com/onmoim/server/user/service/UserServiceTest.java
Labels: 💻 refactor

#79 [User] User 엔티티 내 Location 연관 관계 매핑
  src/main/java/com/onmoim/server/common/exception/ErrorCode.java
  src/main/java/com/onmoim/server/initializer/DataInitializer.java
  src/main/java/com/onmoim/server/user/dto/request/SignupRequestDto.java
  src/main/java/com/onmoim/server/user/dto/request/UpdateProfileRequestDto.java
  src/main/java/com/onmoim/server/user/dto/response/ProfileResponseDto.java
  src/main/java/com/onmoim/server/user/entity/User.java
  src/main/java/com/onmoim/server/user/mapper/UserMapperCustomImpl.java
  src/main/java/com/onmoim/server/user/service/impl/UserServiceImpl.java
  src/test/java/com/onmoim/server/user/service/UserServiceTest.java
Labels: 💻 refactor
