Repository Onmoim/Onmoim-Backend, pull requests merged in 2025-05, with the labels that each got.

#41 [Test] S3Controller 테스트 코드 개선 및 Spring Security 설정 추가
  build.gradle
  src/main/java/com/onmoim/server/config/SecurityConfig.java
  src/test/java/com/onmoim/server/common/s3/controller/S3ControllerTest.java
Labels: 🧪 test

#45 fix: jwt 오류 수정
  src/main/java/com/onmoim/server/oauth/controller/AuthController.java
  src/main/java/com/onmoim/server/oauth/service/impl/OAuthServiceImpl.java
  src/main/java/com/onmoim/server/security/CustomUserDetails.java
  src/main/java/com/onmoim/server/security/JwtProvider.java
  src/test/java/com/onmoim/server/security/JwtProviderTest.java
Labels: 🛠️ fix

#43 feat: 지역 조회 api
  src/main/java/com/onmoim/server/config/SecurityConfig.java
  src/main/java/com/onmoim/server/initializer/DataInitializer.java
  src/main/java/com/onmoim/server/location/controller/LocationController.java
  src/main/java/com/onmoim/server/location/dto/LocationResponseDto.java
  src/main/java/com/onmoim/server/location/entity/Location.java
  src/main/java/com/onmoim/server/location/repository/LocationRepository.java
  src/main/java/com/onmoim/server/location/service/LocationQueryService.java
  src/main/resources/location.csv
  src/test/java/com/onmoim/server/location/service/LocationServiceTest.java
Labels: ✨ feat

#47 feat: 모임 좋아요(찜) 추가
  src/main/java/com/onmoim/server/group/controller/GroupController.java
  src/main/java/com/onmoim/server/group/dto/request/CreateGroupRequestDto.java
  src/main/java/com/onmoim/server/group/entity/GroupUser.java
  src/main/java/com/onmoim/server/group/entity/Status.java
  src/main/java/com/onmoim/server/group/repository/GroupUserRepository.java
  src/main/java/com/onmoim/server/group/service/GroupService.java
  src/main/java/com/onmoim/server/group/service/GroupUserQueryService.java
  src/test/java/com/onmoim/server/group/service/GroupServiceTest.java
Labels: ✨ feat

#51 [Feature] 모임 게시글 및 이미지 기능 구현
  .gitignore
  build.gradle
  com/onmoim/server/common/image/service/ImageQueryService.java
  com/onmoim/server/post/repository/GroupPostQueryService.java
  com/onmoim/server/post/repository/PostImageQueryService.java
  com/onmoim/server/post/service/GroupPostCommandService.java
  com/onmoim/server/post/service/GroupPostService.java
  com/onmoim/server/post/service/ImagePostService.java
  src/main/java/com/onmoim/server/common/BaseEntity.java
  src/main/java/com/onmoim/server/common/exception/ErrorCode.java
  src/main/java/com/onmoim/server/post/batch/DeletedPostsCleanupScheduler.java
  src/main/java/com/onmoim/server/post/controller/GroupPostController.java
  src/main/java/com/onmoim/server/post/dto/request/CursorPageRequestDto.java
  src/main/java/com/onmoim/server/post/dto/request/GroupPostRequestDto.java
  src/main/java/com/onmoim/server/post/dto/response/CursorPageResponseDto.java
  src/main/java/com/onmoim/server/post/dto/response/GroupPostResponseDto.java
  src/main/java/com/onmoim/server/post/entity/GroupPost.java
  src/main/java/com/onmoim/server/post/entity/GroupPostType.java
  src/main/java/com/onmoim/server/post/entity/Image.java
  src/main/java/com/onmoim/server/post/entity/PostImage.java
  src/main/java/com/onmoim/server/post/entity/PostImageId.java
  src/main/java/com/onmoim/server/post/repository/GroupPostRepository.java
  src/main/java/com/onmoim/server/post/repository/GroupPostRepositoryCustom.java
  src/main/java/com/onmoim/server/post/repository/GroupPostRepositoryCustomImpl.java
  src/main/java/com/onmoim/server/post/repository/ImageRepository.java
  src/main/java/com/onmoim/server/post/repository/PostImageRepository.java
  src/main/java/com/onmoim/server/post/service/GroupPostCommandService.java
  src/main/java/com/onmoim/server/post/service/GroupPostQueryService.java
  src/main/java/com/onmoim/server/post/service/GroupPostService.java
  src/main/java/com/onmoim/server/post/service/ImagePostService.java
  src/test/java/com/onmoim/server/post/controller/GroupPostControllerTest.java
  src/test/java/com/onmoim/server/post/service/GroupPostCommandServiceTest.java
Labels: ✨ feat, 🧪 test, 🗂️ Project

#49 fix: 테스트에 제거된 메서드명 변경
  src/test/java/com/onmoim/server/location/service/LocationServiceTest.java
Labels: 🛠️ fix, 🧪 test

#53 refactor: 지역 데이터 초기화 로직 CommandLineRunner로 변경
  src/main/java/com/onmoim/server/initializer/DataInitializer.java
  src/main/java/com/onmoim/server/security/CustomUserDetails.java
  src/test/java/com/onmoim/server/group/service/GroupQueryServiceTest.java
Labels: 💻 refactor

#52 feat: 모임 (삭제, 탈퇴, 모임장 변경) 구현
  src/main/java/com/onmoim/server/common/BaseEntity.java
  src/main/java/com/onmoim/server/common/exception/ErrorCode.java
  src/main/java/com/onmoim/server/group/aop/NamedLockAspect.java
  src/main/java/com/onmoim/server/group/aop/Retry.java
  src/main/java/com/onmoim/server/group/aop/RetryAspect.java
  src/main/java/com/onmoim/server/group/controller/GroupController.java
  src/main/java/com/onmoim/server/group/dto/request/CreateGroupRequestDto.java
  src/main/java/com/onmoim/server/group/dto/request/GroupRequestConstraints.java
  src/main/java/com/onmoim/server/group/dto/request/TransferOwnerRequestDto.java
  src/main/java/com/onmoim/server/group/dto/response/GroupMembersResponseDto.java
  src/main/java/com/onmoim/server/group/entity/GroupUser.java
  src/main/java/com/onmoim/server/group/repository/GroupUserRepository.java
  src/main/java/com/onmoim/server/group/repository/GroupUserRepositoryCustom.java
  src/main/java/com/onmoim/server/group/repository/GroupUserRepositoryCustomImpl.java
  src/main/java/com/onmoim/server/group/service/GroupQueryService.java
  src/main/java/com/onmoim/server/group/service/GroupService.java
  src/main/java/com/onmoim/server/group/service/GroupUserQueryService.java
  src/test/java/com/onmoim/server/group/service/GroupServiceTest.java
Labels: ✨ feat, 💻 refactor, 🧪 test

#57 fix: swagger + security config 수정
  src/main/java/com/onmoim/server/config/SecurityConfig.java
  src/main/java/com/onmoim/server/config/SwaggerConfig.java
Labels: 🛠️ fix

#58 feat: 모임 회원 조회
  src/main/java/com/onmoim/server/common/exception/ErrorCode.java
  src/main/java/com/onmoim/server/common/exception/GlobalExceptionHandler.java
  src/main/java/com/onmoim/server/group/controller/GroupController.java
  src/main/java/com/onmoim/server/group/dto/response/CursorPageResponseDto.java
  src/main/java/com/onmoim/server/group/dto/response/GroupMembersResponseDto.java
  src/main/java/com/onmoim/server/group/repository/GroupUserRepositoryCustom.java
  src/main/java/com/onmoim/server/group/repository/GroupUserRepositoryCustomImpl.java
  src/main/java/com/onmoim/server/group/service/GroupService.java
  src/main/java/com/onmoim/server/group/service/GroupUserQueryService.java
  src/test/java/com/onmoim/server/group/service/GroupServiceTest.java
Labels: ✨ feat, 🛠️ fix

#59 fix: Security, 테스트 리팩토링
  src/main/java/com/onmoim/server/config/SecurityConfig.java
  src/test/java/com/onmoim/server/TestSecurityConfig.java
  src/test/java/com/onmoim/server/common/s3/controller/S3ControllerTest.java
  src/test/java/com/onmoim/server/group/controller/GroupControllerTest.java
  src/test/java/com/onmoim/server/post/controller/GroupPostControllerTest.java
Labels: 🛠️ fix, 🧪 test
