Repository Onmoim/Onmoim-Backend, pull requests merged in 2025-04, with the labels that each got.

#2 chore: GitHub Actions 배포 재시도 로컬 컨테이너 종료로 인한 테스트 실패 문제 해결
  .github/workflows/deploy.yml
Labels: 🚀 deploy

#23 [Health] HealthCheckController 생성
  src/main/java/com/onmoim/server/health/controller/HealthCheckController.java
Labels: 🚀 deploy

#27 project/checkstyle-with-common-code
  .editorconfig
  .gitattributes
  build.gradle
  checkstyle/naver-checkstyle-rules.xml
  checkstyle/naver-checkstyle-suppressions.xml
  checkstyle/naver-intellij-formatter.xml
  src/main/java/com/onmoim/server/common/BaseEntity.java
  src/main/java/com/onmoim/server/common/exception/CustomException.java
  src/main/java/com/onmoim/server/common/exception/ErrorCode.java
  src/main/java/com/onmoim/server/common/exception/GlobalExceptionHandler.java
  src/main/java/com/onmoim/server/common/response/ResponseHandler.java
  src/main/java/com/onmoim/server/config/JpaAuditingConfig.java
  src/main/java/com/onmoim/server/config/S3Config.java
  src/main/java/com/onmoim/server/config/SwaggerConfig.java
  src/main/java/com/onmoim/server/example/controller/RedisController.java
  src/main/java/com/onmoim/server/example/controller/ResponseController.java
  src/main/java/com/onmoim/server/example/controller/TestController.java
  src/main/java/com/onmoim/server/example/entity/TestEntity.java
  src/main/java/com/onmoim/server/example/repository/TestRepository.java
  src/main/java/com/onmoim/server/example/service/TestService.java
  src/main/java/com/onmoim/server/example/service/impl/TestServiceImpl.java
  src/main/java/com/onmoim/server/health/controller/HealthCheckController.java
Labels: 🗂️ Project

#28 Feature/redisconfig
  src/main/java/com/onmoim/server/config/RedisConfig.java
  src/main/java/com/onmoim/server/example/controller/TestController.java
Labels: 🚀 deploy

#33 [Fix] 체크스타일 규칙 준수를 위한 코드 포맷팅
  src/main/java/com/onmoim/server/common/exception/GlobalExceptionHandler.java
  src/main/java/com/onmoim/server/common/s3/dto/FileUploadResponseDto.java
  src/main/java/com/onmoim/server/common/s3/service/FileStorageService.java
  src/main/java/com/onmoim/server/common/s3/service/S3FileStorageService.java
  src/main/java/com/onmoim/server/common/s3/validator/DefaultFileValidator.java
  src/main/java/com/onmoim/server/common/s3/validator/FileValidator.java
  src/main/java/com/onmoim/server/example/controller/ResponseController.java
  src/test/java/com/onmoim/server/common/s3/controller/S3ControllerTest.java
Labels: 🚀 deploy, 🛠️ fix
