Repository Onmoim/Onmoim-Backend, pull requests merged in 2025-07, with the labels that each got.

#84 [User] 구글 로그인/프로필 편집/회원 탈퇴 수정/Authentication 리팩토링
  build.gradle
  src/main/java/com/onmoim/server/common/exception/ErrorCode.java
  src/main/java/com/onmoim/server/meeting/repository/MeetingRepositoryCustom.java
  src/main/java/com/onmoim/server/meeting/repository/MeetingRepositoryCustomImpl.java
  src/main/java/com/onmoim/server/meeting/repository/UserMeetingRepository.java
  src/main/java/com/onmoim/server/meeting/repository/UserMeetingRepositoryCustom.java
  src/main/java/com/onmoim/server/meeting/repository/UserMeetingRepositoryCustomImpl.java
  src/main/java/com/onmoim/server/oauth/service/provider/GoogleOAuthProvider.java
  src/main/java/com/onmoim/server/security/CustomUserDetails.java
  src/main/java/com/onmoim/server/security/JwtProvider.java
  src/main/java/com/onmoim/server/user/entity/User.java
  src/main/java/com/onmoim/server/user/service/impl/UserServiceImpl.java
  src/main/resources/static/test-google-login.html
  src/test/java/com/onmoim/server/InitTest.java
  src/test/java/com/onmoim/server/user/service/UserServiceTest.java
Labels: ✨ feat

#90 refactor: [모임] 상세 조회 수정
  src/main/java/com/onmoim/server/group/dto/GroupDetail.java
  src/main/java/com/onmoim/server/group/dto/response/GroupDetailResponseDto.java
  src/main/java/com/onmoim/server/group/dto/response/GroupInfoResponseDto.java
  src/main/java/com/onmoim/server/group/implement/GroupQueryService.java
  src/main/java/com/onmoim/server/group/repository/GroupRepositoryCustom.java
  src/main/java/com/onmoim/server/group/repository/GroupRepositoryCustomImpl.java
  src/main/java/com/onmoim/server/group/service/GroupService.java
  src/test/java/com/onmoim/server/group/implement/GroupQueryServiceTest.java
Labels: 💻 refactor, 🧪 test

#94 fix: [모임] 상세 조회 수정
  src/main/java/com/onmoim/server/common/exception/ErrorCode.java
  src/main/java/com/onmoim/server/group/dto/request/GroupCreateRequestDto.java
  src/main/java/com/onmoim/server/group/dto/request/GroupUpdateRequestDto.java
  src/main/java/com/onmoim/server/group/dto/response/GroupDetailResponseDto.java
  src/main/java/com/onmoim/server/group/entity/Group.java
Labels: 🛠️ fix

#95 [Group] 가입한/찜한/나와 비슷한 관심사/나와 가까운/최근 본 모임 조회
  src/main/java/com/onmoim/server/common/response/CommonCursorPageResponseDto.java
  src/main/java/com/onmoim/server/group/controller/GroupController.java
  src/main/java/com/onmoim/server/group/dto/response/GroupSummaryResponseDto.java
  src/main/java/com/onmoim/server/group/dto/response/RecentViewedGroupSummaryResponseDto.java
  src/main/java/com/onmoim/server/group/dto/response/cursor/RecentViewCursorPageResponseDto.java
  src/main/java/com/onmoim/server/group/entity/GroupViewLog.java
  src/main/java/com/onmoim/server/group/implement/GroupLikeQueryService.java
  src/main/java/com/onmoim/server/group/implement/GroupQueryService.java
  src/main/java/com/onmoim/server/group/implement/GroupUserQueryService.java
  src/main/java/com/onmoim/server/group/repository/GroupLikeRepository.java
  src/main/java/com/onmoim/server/group/repository/GroupLikeRepositoryCustom.java
  src/main/java/com/onmoim/server/group/repository/GroupLikeRepositoryCustomImpl.java
  src/main/java/com/onmoim/server/group/repository/GroupRepositoryCustom.java
  src/main/java/com/onmoim/server/group/repository/GroupRepositoryCustomImpl.java
  src/main/java/com/onmoim/server/group/repository/GroupUserRepository.java
  src/main/java/com/onmoim/server/group/repository/GroupUserRepositoryCustom.java
  src/main/java/com/onmoim/server/group/repository/GroupUserRepositoryCustomImpl.java
  src/main/java/com/onmoim/server/group/repository/GroupViewLogRepository.java
  src/main/java/com/onmoim/server/group/repository/GroupViewLogRepositoryCustom.java
  src/main/java/com/onmoim/server/group/repository/GroupViewLogRepositoryCustomImpl.java
  src/main/java/com/onmoim/server/group/service/GroupService.java
  src/main/java/com/onmoim/server/user/controller/UserController.java
  src/test/java/com/onmoim/server/group/implement/GroupLikeQueryServiceTest.java
  src/test/java/com/onmoim/server/group/implement/GroupQueryServiceTest.java
  src/test/java/com/onmoim/server/group/implement/GroupUserQueryServiceTest.java
  src/test/java/com/onmoim/server/group/service/GroupServiceTest.java
Labels: ✨ feat

#100 [User] 프로필 조회 필드 추가
  src/main/java/com/onmoim/server/group/repository/GroupLikeRepository.java
  src/main/java/com/onmoim/server/group/repository/GroupLikeRepositoryCustom.java
  src/main/java/com/onmoim/server/group/repository/GroupLikeRepositoryCustomImpl.java
  src/main/java/com/onmoim/server/group/repository/GroupUserRepositoryCustom.java
  src/main/java/com/onmoim/server/group/repository/GroupUserRepositoryCustomImpl.java
  src/main/java/com/onmoim/server/group/repository/GroupViewLogRepositoryCustom.java
  src/main/java/com/onmoim/server/group/repository/GroupViewLogRepositoryCustomImpl.java
  src/main/java/com/onmoim/server/user/dto/response/ProfileResponseDto.java
  src/main/java/com/onmoim/server/user/dto/response/UserCategoryResponseDto.java
  src/main/java/com/onmoim/server/user/entity/User.java
  src/main/java/com/onmoim/server/user/mapper/UserMapperCustomImpl.java
  src/main/java/com/onmoim/server/user/repository/UserCategoryRepository.java
Labels: ✨ feat

#101 [Meeting] 다가오는 일정 조회
  src/main/java/com/onmoim/server/meeting/controller/MeetingController.java
  src/main/java/com/onmoim/server/meeting/dto/request/UpcomingMeetingsRequestDto.java
  src/main/java/com/onmoim/server/meeting/dto/response/MeetingSummaryResponseDto.java
  src/main/java/com/onmoim/server/meeting/dto/response/UpcomingMeetingCursorPageResponseDto.java
  src/main/java/com/onmoim/server/meeting/repository/MeetingRepositoryCustom.java
  src/main/java/com/onmoim/server/meeting/repository/MeetingRepositoryCustomImpl.java
  src/main/java/com/onmoim/server/meeting/service/MeetingQueryService.java
  src/main/java/com/onmoim/server/meeting/service/MeetingService.java
  src/test/java/com/onmoim/server/meeting/service/MeetingQueryServiceTest.java
Labels: ✨ feat
